name: gresky
services:
  - name: code-server
    dockerfile_path: Dockerfile.code-server
    http_port: 8443
    routes:
      - path: /
    envs:
      - key: PASSWORD
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
  - name: codex-agent
    dockerfile_path: Dockerfile.codex
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
