# .do/app.yaml

name: gresky

services:
  - name: code-server
    dockerfile_path: Dockerfile.code-server
    github:
      branch: main
    http_port: 8443
    routes:
      - path: /
    envs:
      - key: PASSWORD
        type: SECRET
      - key: DOMAIN
        type: GENERAL
      - key: EMAIL
        type: GENERAL
      - key: BASIC_AUTH_USER
        type: SECRET
      - key: BASIC_AUTH_PASS_HASH
        type: SECRET

  - name: codex-agent
    dockerfile_path: Dockerfile.codex
    github:
      branch: main
    envs:
      - key: OPENAI_API_KEY
        type: SECRET

